version: "3"
networks:
  petstore:
    external: true

services:
  petstore:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - DB_URL=postgres://db-user:db-password@petstore-db:5432/petstore?sslmode=disable
      - PORT=8080
      - DIAG_PORT=8081
    depends_on:
      - petstore-db
      - flyway
    networks:
      - petstore

  petstore-db:
    image: postgres:9.6
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
    healthcheck:
      test: PGPASSWORD='db-password' psql -U db-user --command='SELECT 1'
      interval: 1s
      timeout: 2s
      retries: 5
    networks:
      - petstore

  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://petstore-db:5432/petstore -user=db-user -password=db-password migrate
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - petstore-db
    networks:
      - petstore

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin@petstore
#      PGADMIN_DEFAULT_PASSWORD: pgadmin
#    ports:
#      - 5050:5050
#    networks:
#      - petstore
