// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package withdb

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type categoryTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *categoryTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("category").
func (v *categoryTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *categoryTableType) Columns() []string {
	return []string{"id", "name", "is_visible", "created_at", "updated_at"}
}

// NewStruct makes a new struct for that view or table.
func (v *categoryTableType) NewStruct() reform.Struct {
	return new(category)
}

// NewRecord makes a new record for that table.
func (v *categoryTableType) NewRecord() reform.Record {
	return new(category)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *categoryTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// categoryTable represents category view or table in SQL database.
var categoryTable = &categoryTableType{
	s: parse.StructInfo{Type: "category", SQLSchema: "", SQLName: "category", Fields: []parse.FieldInfo{{Name: "ID", Type: "int64", Column: "id"}, {Name: "Name", Type: "string", Column: "name"}, {Name: "IsVisible", Type: "bool", Column: "is_visible"}, {Name: "CreatedAt", Type: "time.Time", Column: "created_at"}, {Name: "UpdatedAt", Type: "time.Time", Column: "updated_at"}}, PKFieldIndex: 0},
	z: new(category).Values(),
}

// String returns a string representation of this struct or record.
func (s category) String() string {
	res := make([]string, 5)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "IsVisible: " + reform.Inspect(s.IsVisible, true)
	res[3] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[4] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *category) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Name,
		s.IsVisible,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *category) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Name,
		&s.IsVisible,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *category) View() reform.View {
	return categoryTable
}

// Table returns Table object for that record.
func (s *category) Table() reform.Table {
	return categoryTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *category) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *category) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *category) HasPK() bool {
	return s.ID != categoryTable.z[categoryTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *category) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int64(i64)
	} else {
		s.ID = pk.(int64)
	}
}

// check interfaces
var (
	_ reform.View   = categoryTable
	_ reform.Struct = (*category)(nil)
	_ reform.Table  = categoryTable
	_ reform.Record = (*category)(nil)
	_ fmt.Stringer  = (*category)(nil)
)

func init() {
	parse.AssertUpToDate(&categoryTable.s, new(category))
}
