FROM golang:1.15 AS builder

RUN mkdir -p /myapp
ADD . /myapp
WORKDIR /myapp

# Добавляем непривилегированного пользователя
RUN useradd -u 10001 myapp

# Собираем бинарный файл
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
   go build -o /myapp ./cmd/myapp

FROM scratch

# Не забываем скопировать /etc/passwd с предыдущего стейджа
COPY --from=builder /etc/passwd /etc/passwd
USER myapp

COPY --from=builder /etc/ssl/certs/ /etc/ssl/certs/
COPY --from=builder /myapp /myapp

CMD ["/myapp"]