// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package withdb

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type petTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *petTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("pet").
func (v *petTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *petTableType) Columns() []string {
	return []string{"id", "name", "category_id", "created_at", "updated_at"}
}

// NewStruct makes a new struct for that view or table.
func (v *petTableType) NewStruct() reform.Struct {
	return new(pet)
}

// NewRecord makes a new record for that table.
func (v *petTableType) NewRecord() reform.Record {
	return new(pet)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *petTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// petTable represents pet view or table in SQL database.
var petTable = &petTableType{
	s: parse.StructInfo{Type: "pet", SQLSchema: "", SQLName: "pet", Fields: []parse.FieldInfo{{Name: "ID", Type: "int64", Column: "id"}, {Name: "Name", Type: "string", Column: "name"}, {Name: "CategoryID", Type: "int64", Column: "category_id"}, {Name: "CreatedAt", Type: "time.Time", Column: "created_at"}, {Name: "UpdatedAt", Type: "time.Time", Column: "updated_at"}}, PKFieldIndex: 0},
	z: new(pet).Values(),
}

// String returns a string representation of this struct or record.
func (s pet) String() string {
	res := make([]string, 5)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "CategoryID: " + reform.Inspect(s.CategoryID, true)
	res[3] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[4] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *pet) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Name,
		s.CategoryID,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *pet) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Name,
		&s.CategoryID,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *pet) View() reform.View {
	return petTable
}

// Table returns Table object for that record.
func (s *pet) Table() reform.Table {
	return petTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *pet) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *pet) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *pet) HasPK() bool {
	return s.ID != petTable.z[petTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *pet) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int64(i64)
	} else {
		s.ID = pk.(int64)
	}
}

// check interfaces
var (
	_ reform.View   = petTable
	_ reform.Struct = (*pet)(nil)
	_ reform.Table  = petTable
	_ reform.Record = (*pet)(nil)
	_ fmt.Stringer  = (*pet)(nil)
)

func init() {
	parse.AssertUpToDate(&petTable.s, new(pet))
}
